name: parkour
main: net.xrayfun.parkour.Main
version: 1.0
author: XRayFun_GF

commands:
  parkour:
    permission: parkour.base
    usage: /<command> help

permissions:
  parkour.admin:
    default: op
    children:
      parkour.base: true
  parkour.base:
    default: true